# Generated by Django 4.2.9 on 2024-01-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(db_column='Nome')),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Categoriasdocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, db_column='Nome', null=True)),
            ],
            options={
                'db_table': 'CategoriasDocumentos',
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emaildestino', models.TextField(blank=True, db_column='EmailDestino', null=True)),
                ('emailenviar', models.TextField(blank=True, db_column='EmailEnviar', null=True)),
                ('senhaenviar', models.TextField(blank=True, db_column='SenhaEnviar', null=True)),
                ('stmp', models.TextField(blank=True, db_column='STMP', null=True)),
                ('porta', models.IntegerField(blank=True, db_column='Porta', null=True)),
            ],
            options={
                'db_table': 'Configuracoes',
            },
        ),
        migrations.CreateModel(
            name='Curriculoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(db_column='File')),
                ('nome', models.TextField(blank=True, db_column='Nome', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('telefone', models.TextField(blank=True, db_column='Telefone', null=True)),
            ],
            options={
                'db_table': 'Curriculoes',
            },
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(db_column='Nome')),
                ('cidade', models.TextField(db_column='Cidade')),
                ('estado', models.TextField(db_column='Estado')),
                ('email', models.TextField(db_column='Email')),
                ('tel', models.TextField(blank=True, db_column='Tel', null=True)),
                ('cel', models.TextField(db_column='Cel')),
                ('enderecomaps', models.TextField(blank=True, db_column='EnderecoMaps', null=True)),
            ],
            options={
                'db_table': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Sliderhomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('subtitulo', models.TextField(blank=True, db_column='SubTitulo', null=True)),
                ('linkbotao', models.TextField(blank=True, db_column='LinkBotao', null=True)),
                ('ativo', models.IntegerField(db_column='Ativo')),
                ('foto', models.ImageField(upload_to='images/')),
                ('video', models.TextField(blank=True, db_column='Video', null=True)),
                ('textobotao', models.TextField(blank=True, db_column='TextoBotao', null=True)),
            ],
            options={
                'db_table': 'SliderHomes',
            },
        ),
        migrations.CreateModel(
            name='Tabelanutricionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorenergetico', models.TextField(blank=True, db_column='ValorEnergetico', null=True)),
                ('carboidratostotais', models.TextField(blank=True, db_column='CarboidratosTotais', null=True)),
                ('acucarestotais', models.TextField(blank=True, db_column='AcucaresTotais', null=True)),
                ('proteinas', models.TextField(blank=True, db_column='Proteinas', null=True)),
                ('gordurastotais', models.TextField(blank=True, db_column='GordurasTotais', null=True)),
                ('gordurassaturadas', models.TextField(blank=True, db_column='GordurasSaturadas', null=True)),
                ('gordurastrans', models.TextField(blank=True, db_column='GordurasTrans', null=True)),
                ('fibraalimentar', models.TextField(blank=True, db_column='FibraAlimentar', null=True)),
                ('sodio', models.TextField(blank=True, db_column='Sodio', null=True)),
                ('infos', models.TextField(blank=True, db_column='Infos', null=True)),
            ],
            options={
                'db_table': 'TabelaNutricionals',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, db_column='Nome', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
            ],
            options={
                'db_table': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Productshomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, db_column='Nome', null=True)),
                ('img', models.TextField(blank=True, db_column='Img', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
                ('categoriaid', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.categorias')),
            ],
            options={
                'db_table': 'ProductsHomes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('preco', models.FloatField(db_column='Preco')),
                ('foto_principal', models.ImageField(upload_to='images/')),
                ('foto_secundaria', models.ImageField(upload_to='images/')),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('modopreparo', models.TextField(blank=True, db_column='ModoPreparo', null=True)),
                ('conservacao', models.TextField(blank=True, db_column='Conservacao', null=True)),
                ('codigobarras', models.TextField(blank=True, db_column='CodigoBarras', null=True)),
                ('ingredientes', models.TextField(blank=True, db_column='Ingredientes', null=True)),
                ('categoriaid', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.categorias')),
                ('idnutricional', models.ForeignKey(blank=True, db_column='IdNutricional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tabelanutricionals')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=50, null=True)),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('subtitulo', models.CharField(blank=True, db_column='SubTitulo', max_length=100, null=True)),
                ('miniatura', models.ImageField(null=True, upload_to='images/')),
                ('categoriaid', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.categoriasdocumentos')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
    ]
