# Generated by Django 4.2.9 on 2024-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
