# Generated by Django 4.2.9 on 2024-02-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='atributos',
            field=models.ManyToManyField(to='home.productsattributes'),
        ),
    ]
