# Generated by Django 4.2.9 on 2024-02-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productsattributes_products_atributos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantes',
            name='cel',
            field=models.CharField(db_column='Cel', max_length=25),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='cidade',
            field=models.CharField(db_column='Cidade', max_length=50),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='email',
            field=models.CharField(db_column='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='enderecomaps',
            field=models.CharField(blank=True, db_column='EnderecoMaps', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='estado',
            field=models.CharField(db_column='Estado', max_length=2),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='nome',
            field=models.CharField(db_column='Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='representantes',
            name='tel',
            field=models.CharField(blank=True, db_column='Tel', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='nome',
            field=models.CharField(blank=True, db_column='Nome', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.CharField(blank=True, db_column='Url', max_length=255, null=True),
        ),
    ]
