# Generated by Django 4.2.9 on 2024-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_representantes_cel_alter_representantes_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='endereco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
