# Generated by Django 4.2.9 on 2024-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_representantes_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='cep',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
