# Generated by Django 4.2.9 on 2024-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_categoriasdocumentos_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderhomes',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='sliderhomes',
            name='video',
        ),
        migrations.AddField(
            model_name='sliderhomes',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sliderhomes',
            name='subtitulo',
            field=models.CharField(blank=True, db_column='SubTitulo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sliderhomes',
            name='textobotao',
            field=models.CharField(blank=True, db_column='TextoBotao', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sliderhomes',
            name='titulo',
            field=models.CharField(blank=True, db_column='Titulo', max_length=50, null=True),
        ),
    ]
