# Generated by Django 4.2.9 on 2024-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_sliderhomes_ativo_remove_sliderhomes_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhomes',
            name='linkbotao',
            field=models.CharField(blank=True, db_column='LinkBotao', max_length=255, null=True),
        ),
    ]
