# Generated by Django 4.2.9 on 2024-02-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sliderhomes_linkbotao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='codigobarras',
            field=models.ImageField(blank=True, default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='acucarestotais',
            field=models.FloatField(blank=True, db_column='AcucaresTotais', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='carboidratostotais',
            field=models.FloatField(blank=True, db_column='CarboidratosTotais', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='fibraalimentar',
            field=models.FloatField(blank=True, db_column='FibraAlimentar', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='gordurassaturadas',
            field=models.FloatField(blank=True, db_column='GordurasSaturadas', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='gordurastotais',
            field=models.FloatField(blank=True, db_column='GordurasTotais', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='gordurastrans',
            field=models.FloatField(blank=True, db_column='GordurasTrans', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='infos',
            field=models.CharField(blank=True, db_column='Infos', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='proteinas',
            field=models.FloatField(blank=True, db_column='Proteinas', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='sodio',
            field=models.FloatField(blank=True, db_column='Sodio', null=True),
        ),
        migrations.AlterField(
            model_name='tabelanutricionals',
            name='valorenergetico',
            field=models.FloatField(blank=True, db_column='ValorEnergetico', null=True),
        ),
        migrations.CreateModel(
            name='ProdutoFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='images/')),
                ('produtoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
    ]
