# Generated by Django 4.2.9 on 2024-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_products_codigobarras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(null=True, upload_to='images/')),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Produtos Categoria'},
        ),
        migrations.AlterModelOptions(
            name='categoriasdocumentos',
            options={'verbose_name_plural': 'Documentos Categoria'},
        ),
        migrations.AlterModelOptions(
            name='configuracoes',
            options={'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='curriculoes',
            options={'verbose_name_plural': 'Currículos'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productsattributes',
            options={'verbose_name_plural': 'Produtos - Atributos'},
        ),
        migrations.AlterModelOptions(
            name='produtofotos',
            options={'verbose_name_plural': 'Produtos - Fotos'},
        ),
        migrations.AlterModelOptions(
            name='representantes',
            options={'verbose_name_plural': 'Representantes'},
        ),
        migrations.AlterModelOptions(
            name='sliderhomes',
            options={'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='tabelanutricionals',
            options={'verbose_name_plural': 'Tabela Nutricional'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Vídeos'},
        ),
        migrations.DeleteModel(
            name='Productshomes',
        ),
    ]
