# Generated by Django 4.2.9 on 2024-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_parceiros_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='images/')),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
    ]
