# Generated by Django 4.2.9 on 2024-02-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_galeria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='parceiros',
            options={'verbose_name_plural': 'Parceiros'},
        ),
    ]
